[project]
name = "massist"
version = "0.0.1"
description = "An AI-powered assistant service integrating tools to automate workflows, answer queries, and orchestrate actions across the platform."
authors = [{ name = "Shirsendu Bairagi <shirsendu2001@gmail.com>" }]
requires-python = ">=3.10"

dependencies = [
    "motia[otel]>=1.0.4rc1",
    "pydantic>=2.0",
    "emoji>=2.15.0",
    "omnivoice>=0.1.4",
    "torch==2.8.0+cu128",
    "torchaudio==2.8.0+cu128",
    "iii-sdk==0.10.0",
    "voxcpm>=1.0.2",
]

[dependency-groups]
dev = [
  "changelog-gen>=0.13.5",
  "pre-commit>=4.6.0",
  "pytest>=8.3.4",
  "ruff>=0.8.5",
  "taskipy>=1.14.1",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu128"

[tool.taskipy.tasks]
lint = "ruff check --fix"
format = "ruff format"
dev = "iii -c iii-config.yaml & iii console --enable-flow"
